version: '3.7'

services:
  php-fpm:
    build: docker
    container_name: 'phps'
    ports:
      - '9000:9000'
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: 'nginxs'
    working_dir: /app
    ports:
      - '8080:80'
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:15
    ports:
      - 15432:5432
    container_name: 'postgresqls'
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: 'twitter'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - dump:/app/dump
      - postgresql:/var/lib/postgresql/data

volumes:
  dump:
  postgresql:
